"""rbac_and_v2_forecasts

Revision ID: f7aaa6eba939
Revises: a7b8c9d0e1f2
Create Date: 2026-09-14 16:21:57.360610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7aaa6eba939'
down_revision: Union[str, None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('hospital_id', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('query_params', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_log_hospital_id'), 'access_log', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_access_log_timestamp'), 'access_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_access_log_user_id'), 'access_log', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_hospital_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'hospital_id', name='uq_user_hospital_access')
    )
    op.create_index(op.f('ix_user_hospital_access_hospital_id'), 'user_hospital_access', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_user_hospital_access_user_id'), 'user_hospital_access', ['user_id'], unique=False)
    op.drop_table('playing_with_neon')
    op.create_index(op.f('ix_forecast_runs_created_at'), 'forecast_runs', ['created_at'], unique=False)
    op.add_column('forecasts', sa.Column('target', sa.String(length=50), nullable=False, server_default='admissions'))
    op.add_column('forecasts', sa.Column('prediction_low', sa.Float(), nullable=True))
    op.add_column('forecasts', sa.Column('prediction_high', sa.Float(), nullable=True))
    op.add_column('forecasts', sa.Column('resource_gap', sa.Float(), nullable=True))
    op.add_column('forecasts', sa.Column('capacity_source', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('uq_hospital_date_horizon'), 'forecasts', type_='unique')
    op.create_index('idx_forecast_target', 'forecasts', ['target'], unique=False)
    op.create_unique_constraint('uq_hospital_date_horizon_target', 'forecasts', ['hospital_id', 'forecast_date', 'horizon', 'target'])
    op.drop_constraint(op.f('hospitals_hospital_id_key'), 'hospitals', type_='unique')
    op.create_index(op.f('ix_hospitals_hospital_id'), 'hospitals', ['hospital_id'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_hospitals_hospital_id'), table_name='hospitals')
    op.create_unique_constraint(op.f('hospitals_hospital_id_key'), 'hospitals', ['hospital_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_hospital_date_horizon_target', 'forecasts', type_='unique')
    op.drop_index('idx_forecast_target', table_name='forecasts')
    op.create_unique_constraint(op.f('uq_hospital_date_horizon'), 'forecasts', ['hospital_id', 'forecast_date', 'horizon'], postgresql_nulls_not_distinct=False)
    op.drop_column('forecasts', 'capacity_source')
    op.drop_column('forecasts', 'resource_gap')
    op.drop_column('forecasts', 'prediction_high')
    op.drop_column('forecasts', 'prediction_low')
    op.drop_column('forecasts', 'target')
    op.drop_index(op.f('ix_forecast_runs_created_at'), table_name='forecast_runs')
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.drop_index(op.f('ix_user_hospital_access_user_id'), table_name='user_hospital_access')
    op.drop_index(op.f('ix_user_hospital_access_hospital_id'), table_name='user_hospital_access')
    op.drop_table('user_hospital_access')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_access_log_user_id'), table_name='access_log')
    op.drop_index(op.f('ix_access_log_timestamp'), table_name='access_log')
    op.drop_index(op.f('ix_access_log_hospital_id'), table_name='access_log')
    op.drop_table('access_log')
    # ### end Alembic commands ###
